# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmwxmcQ8uXCkdsWg1GkXE7E7teY-3-oR
"""

pip install streamlit

import streamlit as st

# Page configuration
st.set_page_config(
    page_title="BMI Calculator",
    page_icon="⚖️",
    layout="centered"
)

# Title
st.title("⚖️ BMI Calculator")
st.write("Calculate your Body Mass Index (BMI)")

# Unit selection
unit = st.radio(
    "Select Unit System",
    ["Metric (kg/cm)", "Imperial (lb/in)"]
)

# Inputs
if unit == "Metric (kg/cm)":
    weight = st.number_input(
        "Weight (kg)",
        min_value=1.0,
        max_value=300.0,
        value=70.0
    )

    height = st.number_input(
        "Height (cm)",
        min_value=50.0,
        max_value=250.0,
        value=170.0
    )

    bmi = weight / ((height / 100) ** 2)

else:
    weight = st.number_input(
        "Weight (lb)",
        min_value=1.0,
        max_value=700.0,
        value=154.0
    )

    height = st.number_input(
        "Height (inches)",
        min_value=20.0,
        max_value=100.0,
        value=67.0
    )

    bmi = (weight * 703) / (height ** 2)

# Calculate Button
if st.button("Calculate BMI"):

    st.metric(
        label="Your BMI",
        value=f"{bmi:.2f}"
    )

    if bmi < 18.5:
        st.warning("Category: Underweight")
        st.info("Consider a balanced and nutritious diet.")

    elif bmi < 25:
        st.success("Category: Normal Weight")
        st.info("Great! Maintain your healthy lifestyle.")

    elif bmi < 30:
        st.warning("Category: Overweight")
        st.info("Regular exercise and healthy eating may help.")

    else:
        st.error("Category: Obese")
        st.info("Consider consulting a healthcare professional.")

# Footer
st.markdown("---")
st.caption("Built using Streamlit")